CREATE TABLE IF NOT EXISTS application(
    id UUID PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    phone_number VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL
);